# Generated by Django 5.0.2 on 2024-05-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_alter_poste_as_poste_alter_poste_heure_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='tolerance_time',
            field=models.TimeField(null=True),
        ),
    ]
