# Generated by Django 5.0.2 on 2024-05-02 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_personnel_tolerance_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_month', models.DateField()),
                ('montant', models.IntegerField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.personnel')),
            ],
        ),
    ]
