# Generated by Django 5.0.2 on 2024-05-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_salaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zklecteur',
            name='ip_adresse',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
