# Generated by Django 5.0.2 on 2024-05-13 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profil', '0005_alter_zklecteur_ip_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('genre', models.CharField(max_length=10)),
                ('photo', models.ImageField(blank=True, upload_to='photo_user/')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.poste')),
            ],
        ),
    ]
