# Generated by Django 5.0.2 on 2024-05-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='somme',
            field=models.FloatField(null=True),
        ),
    ]
