# Generated by Django 5.0.2 on 2024-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_remove_profile_email_remove_profile_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo_user/'),
        ),
    ]
