# Generated by Django 5.0.2 on 2024-05-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0009_personnel_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
