# Generated by Django 5.0.2 on 2024-03-31 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horaire',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='Poste',
        ),
    ]
