# Generated by Django 5.0.2 on 2024-03-31 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profil', '0002_delete_horaire_delete_personnel_delete_poste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=64, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('gender', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=100)),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnels',
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_poste', models.CharField(max_length=6, verbose_name='ALIAS_Poste')),
                ('nom_poste', models.CharField(max_length=62, verbose_name='Poste')),
                ('somme', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.personnel', verbose_name='Horaire')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.poste', verbose_name='Poste'),
        ),
    ]
