# Generated by Django 5.0.2 on 2024-03-31 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaire_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.horaire')),
                ('personnel_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.personnel')),
            ],
        ),
    ]
