# Generated by Django 5.0.6 on 2024-06-26 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lecteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.zklecteur'),
        ),
        migrations.AddField(
            model_name='zklecteur',
            name='model_drive',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id_att',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
