# Generated by Django 5.0.2 on 2024-04-03 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.personnel', verbose_name='Personnel'),
        ),
    ]
