# Generated by Django 5.0.2 on 2024-04-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_alter_horaire_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='heure_debut',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='poste',
            name='heure_fin',
            field=models.TimeField(null=True),
        ),
    ]
