# Generated by Django 5.0.2 on 2024-04-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_horaire_date_d_personnel_heure_fixe_personnel_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='image_user',
            field=models.ImageField(blank=True, upload_to='images/employes'),
        ),
    ]
