# Generated by Django 5.0.2 on 2024-04-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_personnel_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='is_present',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='arrival_time',
            field=models.TimeField(default='08:00', null=True),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='departure_time',
            field=models.TimeField(default='19:00', null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='heure_fixe',
            field=models.IntegerField(default='100', null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='image_user',
            field=models.ImageField(blank=True, upload_to='images/employes/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='salary',
            field=models.FloatField(default='0', null=True),
        ),
    ]
