# Generated by Django 5.0.2 on 2024-04-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0009_remove_personnel_image_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='heure_fin',
            field=models.TimeField(default='18:00', null=True),
        ),
    ]
