# Generated by Django 5.0.2 on 2024-04-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0009_personnel_is_present_alter_horaire_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='is_present',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default=1, max_length=24),
            preserve_default=False,
        ),
    ]
