# Generated by Django 5.0.2 on 2024-04-08 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0010_alter_personnel_is_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='image_user',
        ),
    ]
