# Generated by Django 5.0.2 on 2024-04-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0011_remove_personnel_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='arrival_time',
            field=models.TimeField(default='08:30', null=True),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='departure_time',
            field=models.TimeField(default='17:40', null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='Masculin', max_length=100, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='heure_debut',
            field=models.TimeField(default='08:00', null=True),
        ),
        migrations.AlterField(
            model_name='poste',
            name='heure_fin',
            field=models.TimeField(default='08:00', null=True),
        ),
        migrations.AlterField(
            model_name='poste',
            name='somme',
            field=models.IntegerField(default='2500'),
        ),
    ]
