# Generated by Django 5.0.2 on 2024-04-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_profile'),
        ('profil', '0011_zklecteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='horaire_a',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='personnel_a',
        ),
        migrations.RemoveField(
            model_name='horaire',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='poste',
        ),
        migrations.DeleteModel(
            name='Zklecteur',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Horaire',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='Poste',
        ),
    ]
