# Generated by Django 5.0.2 on 2024-04-23 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0015_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaire',
            name='user',
        ),
    ]
