# Generated by Django 5.0.2 on 2024-04-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0016_remove_horaire_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='tolerance_time',
            field=models.TimeField(default='08:30', null=True),
        ),
    ]
