# Generated by Django 5.0.2 on 2024-04-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0017_poste_tolerance_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='arrival_time',
            field=models.DateTimeField(default='08:30', null=True),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='date_d',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='departure_time',
            field=models.DateTimeField(default='17:40', null=True),
        ),
    ]
