# Generated by Django 5.0.2 on 2024-04-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0018_alter_horaire_arrival_time_alter_horaire_date_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='arrival_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='departure_time',
            field=models.DateTimeField(null=True),
        ),
    ]
