# Generated by Django 5.0.2 on 2024-04-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0022_alter_personnel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='id_att',
            field=models.IntegerField(null=True),
        ),
    ]
