# Generated by Django 5.0.2 on 2024-04-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0023_alter_horaire_id_att'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='horaire_a',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='heure_punch',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='id_att',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
