# Generated by Django 5.0.2 on 2024-04-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0024_remove_attendance_horaire_a_attendance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaire',
            name='id_att',
        ),
        migrations.RemoveField(
            model_name='horaire',
            name='punch',
        ),
    ]
