# Generated by Django 5.0.2 on 2024-03-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=10, verbose_name='JOUR')),
                ('mois', models.CharField(max_length=12, verbose_name='MOIS')),
                ('nbre_d', models.IntegerField(verbose_name='Numero')),
                ('heure_arrive', models.TimeField(auto_now=True, max_length=12, null=True, verbose_name='Time_IN')),
                ('heure_sorti', models.TimeField(auto_now=True, max_length=12, null=True, verbose_name='Time_OUT')),
                ('duree', models.IntegerField(verbose_name='Heure_effectue')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_poste', models.CharField(max_length=6, verbose_name='ID_Poste')),
                ('nom_poste', models.CharField(max_length=62, verbose_name='Poste')),
                ('somme', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=64, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('horaire_m', models.IntegerField(null=True, verbose_name='Horaire menseule')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profil.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnels',
            },
        ),
    ]
