# Generated by Django 5.0.2 on 2024-04-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_poste_heure_debut_poste_heure_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaire',
            name='date_d',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='heure_fixe',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=100, verbose_name='Genre'),
        ),
    ]
